# -*- coding: utf-8 -*-
"""OralCancer-5Folds.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P4RgUirxF-lwge_vMFKBHfihJdj_qZCA
"""

from google.colab import drive
drive.mount('/content/drive')

# --- [SETUP KAGGLE E IMPORTS PERMANECEM IGUAIS] ---
!pip install kaggle --quiet
from google.colab import files as gfiles
import os

if not os.path.exists('/root/.kaggle/kaggle.json'):
    uploaded = gfiles.upload()
    !mkdir -p ~/.kaggle
    !mv kaggle.json ~/.kaggle/
    !chmod 600 ~/.kaggle/kaggle.json

if not os.path.exists('./data'):
    !kaggle datasets download -d zaidpy/oral-cancer-dataset
    !unzip -q oral-cancer-dataset.zip -d data

import time, copy, csv
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim import lr_scheduler
import torchvision
from torchvision import datasets, models, transforms
from torch.utils.data import Subset, DataLoader
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, roc_curve, auc
from sklearn.metrics import precision_score, recall_score, f1_score

# --- CONFIGURAÇÕES ---
models_to_run = ["googlenet", "resnet18", "densenet121"]
batch_size = 32
num_epochs = 30
lr = 1.5e-5
n_splits = 5
base_save_dir = "/content/drive/MyDrive/OralCancer5FOLDS"

def safe_makedirs(path):
    if not os.path.exists(path): os.makedirs(path, exist_ok=True)

safe_makedirs(base_save_dir)

# --- DATASET ---
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

data_dir = "./data/Oral cancer Dataset 2.0/OC Dataset kaggle new"
full_dataset = datasets.ImageFolder(data_dir, transform=transform)
num_classes = len(full_dataset.classes)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)
all_indices = list(skf.split(np.arange(len(full_dataset)), full_dataset.targets))

# --- FUNÇÕES DE PLOTAGEM ---

def plot_and_save_metrics(history, model_name, fold_path):
    for metric in ['acc', 'loss']:
        plt.figure()
        plt.plot(history[f'train_{metric}'], label=f'Train {metric}')
        plt.plot(history[f'val_{metric}'], label=f'Val {metric}')
        plt.title(f'{metric.capitalize()} - {model_name}')
        plt.legend()
        plt.savefig(os.path.join(fold_path, f"{model_name}_{metric}.png"))
        plt.close('all')

def plot_and_save_confusion_matrix(y_true, y_pred, class_names, model_name, fold_path, fold_idx):
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(8, 6))
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
    disp.plot(cmap=plt.cm.Blues, values_format='d')
    plt.title(f"Matriz de Confusão - {model_name} (Fold {fold_idx})")
    plt.savefig(os.path.join(fold_path, f"{model_name}_confusion_matrix_fold{fold_idx}.png"))
    plt.close('all')

def plot_and_save_roc_auc(y_true, y_probs, model_name, fold_path, fold_idx):
    fpr, tpr, _ = roc_curve(y_true, y_probs[:, 1])
    roc_auc = auc(fpr, tpr)
    plt.figure()
    plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc:.4f})')
    plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title(f'ROC/AUC - {model_name} (Fold {fold_idx})')
    plt.legend(loc="lower right")
    plt.savefig(os.path.join(fold_path, f"{model_name}_roc_auc_fold{fold_idx}.png"))
    plt.close('all')
    return roc_auc

# --- TREINAMENTO ---
def train_model(model, dataloaders, dataset_sizes, criterion, optimizer, scheduler, num_epochs):
    history = {"train_acc": [], "val_acc": [], "train_loss": [], "val_loss": []}
    best_model_wts = copy.deepcopy(model.state_dict())
    best_acc = 0.0

    for epoch in range(num_epochs):
        for phase in ['train', 'val']:
            if phase == 'train': model.train()
            else: model.eval()

            running_loss, running_corrects = 0.0, 0
            for inputs, labels in dataloaders[phase]:
                inputs, labels = inputs.to(device), labels.to(device)
                optimizer.zero_grad()
                with torch.set_grad_enabled(phase == 'train'):
                    outputs = model(inputs)
                    _, preds = torch.max(outputs, 1)
                    loss = criterion(outputs, labels)
                    if phase == 'train':
                        loss.backward()
                        optimizer.step()
                running_loss += loss.item() * inputs.size(0)
                running_corrects += torch.sum(preds == labels.data)

            if phase == 'train': scheduler.step()

            epoch_acc = running_corrects.double() / dataset_sizes[phase]
            epoch_loss = running_loss / dataset_sizes[phase]
            history[f"{phase}_acc"].append(epoch_acc.item())
            history[f"{phase}_loss"].append(epoch_loss)

            if phase == 'val' and epoch_acc > best_acc:
                best_acc = epoch_acc.item()
                best_model_wts = copy.deepcopy(model.state_dict())

    model.load_state_dict(best_model_wts)
    return model, best_acc, history

# --- EXECUÇÃO PRINCIPAL ---
final_comparison = []
all_models_histories = {}

for model_name in models_to_run:
    m_dir = os.path.join(base_save_dir, model_name)
    safe_makedirs(m_dir)
    f_acc, f_pre, f_rec, f_f1, f_auc = [], [], [], [], []
    fold_histories = []

    for fold, (train_idx, val_idx) in enumerate(all_indices):
        print(f"\nModel: {model_name} | Fold {fold+1}/{n_splits}")
        f_path = os.path.join(m_dir, f"fold_{fold+1}")
        safe_makedirs(f_path)

        train_sub, val_sub = Subset(full_dataset, train_idx), Subset(full_dataset, val_idx)
        dls = {"train": DataLoader(train_sub, batch_size=batch_size, shuffle=True),
               "val": DataLoader(val_sub, batch_size=batch_size, shuffle=False)}
        sizes = {"train": len(train_sub), "val": len(val_sub)}

        if model_name == "resnet18": model = models.resnet18(pretrained=True); model.fc = nn.Linear(model.fc.in_features, num_classes)
        elif model_name == "densenet121": model = models.densenet121(pretrained=True); model.classifier = nn.Linear(model.classifier.in_features, num_classes)
        elif model_name == "googlenet":
            model = models.googlenet(pretrained=True)
            model.aux_logits = False  # Desativa as saídas auxiliares após o carregamento
            model.fc = nn.Linear(model.fc.in_features, num_classes)

        model = model.to(device)
        criterion = nn.CrossEntropyLoss()
        optimizer = optim.Adam(model.parameters(), lr=lr)
        scheduler = lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.1)

        model, best_val_acc, history = train_model(model, dls, sizes, criterion, optimizer, scheduler, num_epochs)
        fold_histories.append(history)

        # Salva Gráficos e os dados numéricos das épocas (pequeno)
        plot_and_save_metrics(history, model_name, f_path)
        pd.DataFrame(history).to_csv(os.path.join(f_path, f"{model_name}_history.csv"), index=False)

        # Avaliação de métricas (Sem salvar CSV de probabilidades por imagem)
        model.eval()
        all_preds, all_labels, all_probs = [], [], []
        with torch.no_grad():
            for inputs, labels in dls["val"]:
                inputs = inputs.to(device)
                outputs = model(inputs)
                probs = torch.nn.functional.softmax(outputs, dim=1)
                _, preds = torch.max(outputs, 1)
                all_preds.extend(preds.cpu().numpy())
                all_labels.extend(labels.numpy())
                all_probs.extend(probs.cpu().numpy())

        all_labels, all_preds, all_probs = np.array(all_labels), np.array(all_preds), np.array(all_probs)

        plot_and_save_confusion_matrix(all_labels, all_preds, full_dataset.classes, model_name, f_path, fold+1)
        current_auc = plot_and_save_roc_auc(all_labels, all_probs, model_name, f_path, fold+1)

        f_acc.append(best_val_acc)
        f_pre.append(precision_score(all_labels, all_preds))
        f_rec.append(recall_score(all_labels, all_preds))
        f_f1.append(f1_score(all_labels, all_preds))
        f_auc.append(current_auc)

    all_models_histories[model_name] = {
        "acc": np.mean([h["train_acc"] for h in fold_histories], axis=0),
        "std": np.std([h["train_acc"] for h in fold_histories], axis=0)
    }

    final_comparison.append({
        "Modelo": model_name,
        "Acc": f"{np.mean(f_acc):.4f} ± {np.std(f_acc):.4f}",
        "Precision": f"{np.mean(f_pre):.4f} ± {np.std(f_pre):.4f}",
        "Recall": f"{np.mean(f_rec):.4f} ± {np.std(f_rec):.4f}",
        "F1": f"{np.mean(f_f1):.4f} ± {np.std(f_f1):.4f}",
        "AUC": f"{np.mean(f_auc):.4f} ± {np.std(f_auc):.4f}"
    })

# --- GRÁFICO COMPARATIVO FINAL ---
plt.figure(figsize=(10, 6))
colors = {'googlenet': 'blue', 'resnet18': 'red', 'densenet121': 'green'}
markers = {'googlenet': 'o', 'resnet18': 's', 'densenet121': '^'}

for model_name in models_to_run:
    mean_acc = all_models_histories[model_name]["acc"]
    std_acc = all_models_histories[model_name]["std"]
    epochs = range(1, num_epochs + 1)
    plt.errorbar(epochs, mean_acc, yerr=std_acc, label=f"{model_name} (Média ± σ)",
                 color=colors[model_name], marker=markers[model_name], capsize=3)

plt.title("Comparação da Acurácia de Treinamento ao Longo das Épocas")
plt.xlabel("Época"); plt.ylabel("Média da Acurácia")
plt.legend(); plt.grid(True, alpha=0.3)
plt.savefig(os.path.join(base_save_dir, "comparativo_treinamento_epocas.png"))
plt.show()

print("\n=== RESUMO FINAL COMPARATIVO ===")
df_results = pd.DataFrame(final_comparison)
print(df_results.to_string(index=False))
df_results.to_csv(os.path.join(base_save_dir, "resultado_final_consolidado.csv"), index=False)

print("\n=== SUCESSO: Gráficos e métricas gerados sem os CSVs de probabilidades! ===")

# --- GRÁFICO COMPARATIVO DE VALIDAÇÃO ---
plt.figure(figsize=(10, 6))
colors = {'googlenet': 'blue', 'resnet18': 'red', 'densenet121': 'green'}
markers = {'googlenet': 'o', 'resnet18': 's', 'densenet121': '^'}

# Primeiro, precisamos estruturar os dados de validação que o loop principal não salvou no dicionário global
val_models_histories = {}

for model_name in models_to_run:
    # Esta parte assume que você ainda tem as variáveis na memória da última execução
    # Se você rodou o código inteiro, vamos extrair os dados de 'val_acc'
    # Nota: Precisamos buscar os históricos que foram salvos na lista durante o loop

    # Vamos recriar a média de validação a partir dos arquivos salvos ou da lógica de fold_histories
    # Se você acabou de rodar, 'fold_histories' contém apenas o do ÚLTIMO modelo.
    # Por segurança, vamos ler direto dos CSVs que seu código salvou no Drive:

    all_folds_val_acc = []
    for fold in range(1, n_splits + 1):
        path_csv = os.path.join(base_save_dir, model_name, f"fold_{fold}", f"{model_name}_history.csv")
        df_hist = pd.read_csv(path_csv)
        all_folds_val_acc.append(df_hist['val_acc'].values)

    mean_val_acc = np.mean(all_folds_val_acc, axis=0)
    std_val_acc = np.std(all_folds_val_acc, axis=0)

    epochs = range(1, num_epochs + 1)
    plt.errorbar(epochs, mean_val_acc, yerr=std_val_acc,
                 label=f"{model_name} (Val Média ± σ)",
                 color=colors[model_name], marker=markers[model_name],
                 capsize=3, linestyle='--') # Linha tracejada para diferenciar do treino

plt.title("Comparação da Acurácia de VALIDAÇÃO ao Longo das Épocas")
plt.xlabel("Época")
plt.ylabel("Média da Acurácia (Validação)")
plt.legend()
plt.grid(True, alpha=0.3)

# Salva o novo gráfico no Drive
plt.savefig(os.path.join(base_save_dir, "comparativo_validacao_epocas.png"))
plt.show()

print(f"=== Sucesso: Gráfico de validação salvo em: {base_save_dir}/comparativo_validacao_epocas.png ===")